<?php ob_start(); ?>
<html>

	<body>

		<?php

		//store the inputs in variables
		$username = $_POST['username'];
		$password = hash('sha512', $_POST['password']);

		//connect to db
		require_once ('db.php');

		//set the SQL SELECT statement
		$sql = "SELECT id FROM admins WHERE username = :username AND password = :password";

		$cmd = $conn -> prepare($sql);
		$cmd -> bindParam(':username', $username, PDO::PARAM_STR, 50);
		$cmd -> bindParam(':password', $password, PDO::PARAM_STR, 128);
		$cmd -> execute();
		$result = $cmd -> fetchAll();

		if (count($result) >= 1) {
			echo 'Logged in Successfully.';

			//access the existing session generated by the server
			session_start();

			foreach ($result as $row) {
				//store the admin's database id in the session object
				$_SESSION['id'] = $row['id'];

				//redirect to admins' list
				header('location:admins.php');
			}
		} else {
			echo 'Invalid Login';
		}

		//disconnect
		$conn = null;
	?>
	</body>
</html>
<?php ob_flush(); ?>
